[package]
name = "http_code_crafters"
version = "0.1.0"
edition = "2024"

[dependencies]
portpicker = "0.1.1"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["sync"] }
